apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ats-system
data:
  # Database configuration
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/ats_db"
  SPRING_SECURITY_USER_ROLES: "ADMIN"
  
  # Ollama configuration
  OLLAMA_MODEL: "phi3"
  OLLAMA_BASE_URL: "http://ollama-service:11434"
  APP_RESUME_ANALYSIS_PROVIDER: "ollama"
  
  # Frontend configuration
  REACT_APP_API_URL: "http://localhost:8080"
  REACT_APP_SOCKET_URL: "http://localhost:9092"
  NODE_ENV: "development"
  WDS_SOCKET_PORT: "0"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ats-system
type: Opaque
data:
  # PostgreSQL credentials (base64 encoded)
  POSTGRES_DB: YXRzX2Ri  # ats_db
  POSTGRES_USER: YXRzX3VzZXI=  # ats_user
  POSTGRES_PASSWORD: YXRzX3Bhc3N3b3JkMTIz  # ats_password123
  
  # JWT and Spring Security (base64 encoded)
  JWT_SECRET: bXlfc3VwZXJfc2VjcmV0X2p3dF9rZXlfZm9yX2F0c19zeXN0ZW0=  # my_super_secret_jwt_key_for_ats_system
  SPRING_SECURITY_USER_NAME: YWRtaW4=  # admin
  SPRING_SECURITY_USER_PASSWORD: YWRtaW5wYXNzd29yZA==  # adminpassword
  
  # Email configuration (base64 encoded - using dummy values for local)
  MAIL_USERNAME: dGVzdEBleGFtcGxlLmNvbQ==  # test@example.com
  MAIL_PASSWORD: dGVzdHBhc3N3b3Jk  # testpassword
  
  # LinkedIn OAuth (base64 encoded - using dummy values for local)
  LINKEDIN_CLIENT_ID: ZHVtbXlfY2xpZW50X2lk  # dummy_client_id
  LINKEDIN_CLIENT_SECRET: ZHVtbXlfY2xpZW50X3NlY3JldA==  # dummy_client_secret 