apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ats-system
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ats-frontend:local  # We'll build this locally
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
      initContainers:
      - name: wait-for-backend
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z backend-service 8080; do echo waiting for backend; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ats-system
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001
  selector:
    app: frontend 